version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Make sure this is the correct file name
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/client  # Mount the current directory to /client inside the container
    command: ["npm", "start"]
