version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Make sure this is the correct file name
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/backend  # Mount the current directory to /backend inside the container (optional)
    command: ["npm", "start"]
